f093:
  time_constant: 0
  NEP: 1.5e-17 # W / sqrt(s)
  knee: 1.0 # Hz
  efficiency: 0.1
  gain_error: 5.e-2
  nu: [7.40e+10, 7.50e+10, 7.60e+10, 7.70e+10, 7.80e+10, 7.90e+10, 8.00e+10, 8.10e+10, 8.20e+10, 8.30e+10, 8.40e+10, 8.50e+10, 8.60e+10, 8.70e+10, 8.80e+10, 8.90e+10, 9.00e+10, 9.10e+10, 9.20e+10, 9.30e+10, 9.40e+10, 9.50e+10, 9.60e+10, 9.70e+10, 9.80e+10, 9.90e+10, 1.00e+11, 1.01e+11, 1.02e+11, 1.03e+11, 1.05e+11]
  tau: [0.0, 0.970, 1.000, 0.940, 0.890, 0.940, 0.870, 0.900, 0.850, 0.780, 0.820, 0.710, 0.700, 0.780, 0.700, 0.680, 0.610, 0.530, 0.640, 0.560, 0.570, 0.550, 0.450, 0.440, 0.370, 0.360, 0.300, 0.310, 0.340, 0.310, 0.0]
