f093:
  time_constant: 0
  NEP: 3.e-5 # pW / sqrt(s)
  knee: 1.0 # Hz
  efficiency: 0.1
  gain_error: 5.e-2
  nu: [74.0, 75.0, 76.0, 77.0, 78.0, 79.0, 80.0, 81.0, 82.0, 83.0, 84.0, 85.0, 86.0, 87.0, 88.0, 89.0, 90.0, 91.0, 92.0, 93.0, 94.0, 95.0, 96.0, 97.0, 98.0, 99.0, 100.0, 101.0, 102.0, 103.0, 105.0]
  tau: [0.0, 0.970, 1.000, 0.940, 0.890, 0.940, 0.870, 0.900, 0.850, 0.780, 0.820, 0.710, 0.700, 0.780, 0.700, 0.680, 0.610, 0.530, 0.640, 0.560, 0.570, 0.550, 0.450, 0.440, 0.370, 0.360, 0.300, 0.310, 0.340, 0.310, 0.0]
