default:
  description: A 60-second stare at 45deg elevation.
  start_time: '2022-02-10T06:00:00'
  integration_time: 60
  scan_pattern: daisy
  pointing_frame: az_el
  pointing_units: degrees
  scan_center: [150, 10]
  scan_radius: 0
  scan_period: 60
  sample_rate: 50

stare:
  description: A 60-second zenith stare.
  integration_time: 60
  scan_pattern: back-and-forth
  pointing_frame: az_el
  scan_center: [0, 90]
  scan_radius: 0
  pointing_units: degrees
  scan_period: 120
  sample_rate: 20
    
daisy:
  description: 'A daisy scan with a 2-degree radius.'
  pointing_frame: ra_dec
  pointing_units: degrees
  scan_pattern: daisy
  scan_center: [150., 10]
  scan_radius: 2
  scan_period: 20
  sample_rate: 50
  
# DAISY-2deg_4ra_10dec_600s:
#   description: ''
#   start_time: '2022-07-01T08:00:00'
#   integration_time: 600
#   scan_pattern: daisy
#   scan_options:
#     k: 3.1416
#   scan_center:
#   - 4
#   - 10
#   scan_radius:
#   - 2
#   - 2
#   pointing_frame: ra_dec
#   pointing_units: degrees
#   scan_period: 60
#   sample_rate: 20
#   
# BAF_5deg_45az_45el_60s:
#   description: ''
#   start_time: '2022-07-01T08:00:00'
#   integration_time: 60
#   scan_pattern: back-and-forth
#   scan_options:
#     k: 3.1416
#   scan_center:
#   - 45
#   - 45
#   scan_radius:
#   - 5
#   - 5
#   pointing_frame: az_el
#   pointing_units: degrees
#   scan_period: 60
#   sample_rate: 20
#   