AliCPT:
  description: Ali CMB Polarization Telescope
  region: ngari
  latitude: -32.326
  longitude: 80.026
  altitude: 5050
  documentation: https://www.nist.gov/measuring-cosmos/ali-cmb-polarization-telescope-alicpt

ALMA:
  description: Atacama Large Millimeter Array
  region: chajnantor
  latitude: -23.0294
  longitude: -67.7548
  altitude: 5064
  documentation: https://www.almaobservatory.org/en/home/

APEX:
  description: Atacama Pathfinder Experiment
  region: chajnantor
  latitude: -23.0058
  longitude: -67.7592
  altitude: 5064
  documentation: https://www.eso.org/public/teles-instr/apex/

ACT:
  description: Atacama Cosmology Telescope
  region: chajnantor
  latitude: -22.9586
  longitude: -67.7878
  altitude: 5190
  documentation: https://act.princeton.edu/

GBT:
  description: Green Bank Telescope
  region: green_bank
  latitude: 38.4331
  longitude: -79.8398
  altitude: 825
  documentation: https://greenbankobservatory.org/science/telescopes/gbt/

IRAM:
  description: IRAM 30m telescope
  region: pico_veleta
  latitude: 37.066161
  longitude: -3.392719
  altitude: 2850
  documentation: https://iram-institute.org/observatories/30-meter-telescope/

JCMT:
  description: James Clerk Maxwell Telescope
  region: mauna_kea
  latitude: 19.8228
  longitude: -155.4770
  altitude: 4092
  documentation: https://www.eaobservatory.org/jcmt/

LMT:
  description: Large Millimeter Telescope
  region: sierra_negra
  latitude: 18.9858
  longitude: -97.3147
  altitude: 4640
  documentation: http://lmtgtm.org/

NOEMA:
  description: Northern Extended Millimeter Array
  region: pic_de_bure
  latitude: 44.63389
  longitude: 5.90792
  altitude: 2552
  documentation: https://iram-institute.org/observatories/noema/

QUIJOTE:
  description: Q-U-I JOint Tenerife Experiment
  region: pico_veleta
  latitude: 28.30026
  longitude: -16.51012
  altitude: 2390
  documentation: https://research.iac.es/proyecto/quijote/pages/en/telescopes.php

SPT:
  description: South Pole Telescope
  region: south_pole
  latitude: 0.
  longitude: -90.
  altitude: 2800
  documentation: https://astro.uchicago.edu/research/spt.php

SRT:
  description: Sardinia Radio Telescope
  region: san_basilio
  latitude: 39.4928
  longitude: 9.2450
  altitude: 600
  documentation: https://en.wikipedia.org/wiki/Sardinia_Radio_Telescope
