name: Test Nifty Maria

on: 
  push:
  pull_request:

jobs:
  test-nifty-maria:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout maria
        uses: actions/checkout@v4

      - name: Checkout nifty_maria (inside CMB_denoising)
        uses: actions/checkout@v4
        with:
          repository: jwuerzinger/CMB_denoising
          path: CMB_denoising
          ref: pixi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pixi
        run: |
          curl -fsSL https://pixi.sh/install.sh | bash
          echo "$HOME/.pixi/bin" >> $GITHUB_PATH

      - name: Ensure pip in pixi environment
        run: |
          cd CMB_denoising
          pixi run python -m ensurepip --upgrade
          pixi run python -m pip install --upgrade pip

      - name: Install maria in pixi environment
        run: |
          cd CMB_denoising
          pixi run pip install -e ../

      - name: Install nifty 8 in pixi environment
        run: |
          cd CMB_denoising
          pixi run pip install "git+https://gitlab.mpcdf.mpg.de/ift/nifty.git@NIFTy_8#egg=nifty8"
      
      - name: Install nifty_maria in pixi environment
        run: |
          cd CMB_denoising
          pixi run pip install -e nifty_maria/

      - name: Run tests with pixi
        run: |
          cd CMB_denoising/nifty_maria
          pixi run pytest -q

      - name: Run atmos test
        run: |
          # cd CMB_denoising/nifty_maria/steering
          cd CMB_denoising
          pixi run pip list
          pixi run python nifty_maria/steering/test_steering.py --config test --fit_atmos True --fit_map False
